{
  "parent": "item/generated",
  "textures": {
    "layer0": "villageevolution:item/blueprint_wall_gate"
  }
}
pluginManagement {
    repositories {
        maven { url = "https://maven.minecraftforge.net/" }
        mavenCentral()
        gradlePluginPortal()
    }
}
rootProject.name = "villagerevolutionmod"
